### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#142]
- [ ] Update app manager to get sorted versions
- [ ] Download progress is blocking the UI
- [x] Clean old grid-ui releases
