### ISSUE TITLE
Grid API

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#275]
I think this should be a joint effort with the docs initiative.

### Persistence
unlocks:
- [x] user config values (#23)
- [x] registries (#281)
- [x] plugin development path on config

### Configuration
- [x] flag preview (#247)
- [ ] PoC: flag values as functions (#282)  📄
- [ ] nested or conditional flag values 📄
- [ ] flag grouping by category  📄
- [ ] new flag type: checkbox 📄
- [ ] new flag type: select multiple 📄
- [ ] new flag type: fallback field 📄
- [ ] text field: default value without producing flag output
- [ ] text field: placeholder 📄
- [ ] help bubbles 📄
- [ ] show/hide fields based on other field values 📄
- [ ] path to custom config files 📄
- [ ] virtual config files 📄
- [ ] backwards compatibility (version range for the flags)  📄

### Services
- executor types  📄
  - [x] binary
  - [ ] docker
  - [ ] npm
  - [ ] binary with supporting files
  - [ ] installation script
- [x] more powerful terminal
- [ ] native-looking terminal
- [ ] service actions (#280)
- [ ] Run more than one instance of a service
- [ ] Services with more than one clients (think of ETH 2.0)

### Services interoperability
- [ ] API for apps  📄
    - [x] OS notifications
    - [x] stdin custom method
    - [x] handle data
    - [x] Request service interaction from apps (by type or name, with chain as parameter?)
    - [ ] persistence (fs, memory)

### Plugin / App distribution
- [ ] Scopes: grid repo, plugins.json, apps.json, development  📄
- [ ] Registries (#281)
  - [ ] add/remove 
  - [ ] browse plugins/apps from each registry or all together *Needs UI*

"How to use web3 over rpc, in a way that's closer to what they're used to" 

📄<- this is for documentation

**Comment by evertonfraga** [comment]
On the Linux world, the package managers have the ability to add other registers, that could be private, third-party, community maintained, etc.

Example 1: 
https://wiki.debian.org/SourcesList

Example 2: 
NPM registry url: https://gemfury.com/help/npm-registry/

The difference is that it seems you can only have one npm registry url, whereas with sources list, you can have as many source list as you can — favoring decentralization in the long run.

**Comment by evertonfraga** [comment]
### Priorities 
1. persistence (ongoing: #23)
1. flag preview (#247)
1. service actions (#280)
1. Profiles
1. Registries (#281)
1. flag values as functions (#282)
