### ISSUE TITLE
As a user, I want to use Grid in a minimal way, so I can get my job done with fewer clicks

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#316]
![image](https://user-images.githubusercontent.com/47108/60735825-c38ccd80-9f22-11e9-9324-6be278dd8dac.png)

#### general flow
- [x] lift condition to quit app when all windows are closed #120 
- [x] grid-mini should open on startup, instead of  grid-ui
- [x] grid-mini should open on a frameless window, without control buttons
- [x] menubar button should control grid-mini visibility, instead of instantiate-and-destroy

#### grid-mini UI
- [x] list of plugins (no grouping atm, but respecting plugin order)
- [x] each ListItem should include switch and inform the following states: 

> 1. switch off
> 1. switch on
> 1. downloading (progressbar)
> 1. starting >>> started

Specs of the mini window (electron config):
- [x] `frame: false` to disable title bar and control buttons
- [x] `transparent: true`, so we can customize the window tip
- [x] initially, size to 330 x 420 
- [x] click on menu bar icon should toggle window visibility `window.hide() or window.show()`

i presume we’ll use the [menubar package](https://github.com/maxogden/menubar), that’ll help with automatic window positioning for all OSes.

**Comment by evertonfraga** [comment]
Specs of the mini window:
- [ ] `frame: false` to disable title bar and control buttons
- [ ] `transparent: true`
- [ ] initially, size to 330 x 420 
- [ ] any click outside the window should hide it (`window.on('blur', () => window.hide())`)
- [ ] click on menu bar icon should toggle window visibility `window.hide() or window.show()`
- [ ] disable resizing `win.on('resize', event => { event.preventDefault() })`

**Comment by evertonfraga** [comment]
Solved in #317.
