### ISSUE TITLE
As a user, I want to use Grid while offline, so that I can enjoy additional security and usability

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#320]
- [x] Ship with Grid ui instance #345 
- [ ] Ship with select clients/nodes
- [ ] Handle electron-app-manager requests gracefully on startup
- [ ] Handle grid-ui version menu gracefully
- [ ] Handle plugins and registries requests gracefully
- [ ] Only use local assets (css, images)
