### ISSUE TITLE
Improve linux package information

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#403]
on the picture, .deb opened on ubuntu

- [ ] Linux apps often describe better the app, we're using only "Ethereum Grid". Electron builder has an override for that in linux
- [ ] screenshot(s)
- [ ] license information
- [ ] change website from github repo to grid.ethereum.org
- [ ] publish to Snap store

references: 
https://www.electron.build/configuration/linux
https://www.electron.build/configuration/configuration#overridable-per-platform-options

![image](https://user-images.githubusercontent.com/47108/62319578-46df0780-b46c-11e9-8cf3-5e2a702936a9.png)
