### ISSUE TITLE
As a developer, I want to test Grid-UI build channels from the Grid [shell] interface, so we can ensure app quality standards

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#87]
## Branches
- `master`: production
- `dev`: base and staging

## Channels
- `prerelease`: automatically triggered from `master` branch
- `production`: manually triggered from `master` branch
- `nightly`: daily builds from `dev` branch

## Tasks 

- [x] Create `dev` branch
- [x] Schedule nightly builds
- [x] Publish nightly builds to Github with `-nightly` channel
- [x] Update devops document and publish
